const COPY = {
  zh: {
    "tdk.title": "ST MCU Selector | STMicroelectronics",
    "tdk.description": "ST MCU Selector：按必须满足的规格、已核实的竞品参数或 STM32 订货号，从意法半导体公开 MCU 数据库给出最多三个候选。结果是短名单，设计前需核对 datasheet。",
    "tdk.keywords": "ST MCU Selector, STM32, MCU 选型, 订货号, 竞品对照",
    "db.loading": "器件库加载中",
    "db.ready": "器件库就绪",
    "db.readyCount": "器件库就绪 · {count} 个订货号",
    "db.notReady": "器件库未就绪",
    "db.offline": "无法连接选型服务",
    "messageBar": "数据库匹配只给候选；最多给出三个订货号。这是短名单，不是设计签核。封装引脚、外设并发、认证、价格和供货仍须核对当前 datasheet。",
    "modes.aria": "选择任务",
    "lang.aria": "选择语言",
    "tab.recommend.head": "推荐",
    "tab.recommend.body": "一句话需求或竞品对照，最多三颗候选",
    "tab.inspect.head": "查看订货号",
    "tab.inspect.body": "核对其在库里是什么",
    "nl.label": "用一句话描述",
    "nl.placeholder": "例如：电机控制要 USB；有没有跟 GD32H779 性能接近的，最好从 H5 里找；替换某厂订货号；查看 STM32G474RET3。",
    "nl.notes": "点推荐后直接出候选。硬约束可在左侧改。不承诺价格和交期。",
    "nl.notesLlm": "DeepSeek 会把这句话改成硬约束或竞品规格，点推荐后由数据库出候选。",
    "nl.notesRules": "未配置 DeepSeek 时按关键词抽取。点推荐后由数据库出候选。",
    "drop.title": "可选上传竞品规格书 PDF 或截图；可拖拽到此处。",
    "drop.notes": "电子版/清晰截图，8 MB 以内，文件不保存。扫描件或糊图抽不出字时，请把关键规格粘进输入框。",
    "drop.fileChosen": "已选择文件",
    "drop.needPdf": "请上传 PDF 规格书或清晰截图（PNG / JPG / WebP）。",
    "drop.tooLarge": "文件请控制在 8 MB 以内。",
    "drop.ocrImage": "正在识别图片中的规格…",
    "drop.ocrPdf": "正在从规格书抽取规格…",
    "submit.recommend": "推荐",
    "must.summary": "硬约束（可改后再点推荐）",
    "field.application": "应用",
    "field.frequency": "主频至少 (MHz)",
    "field.flash": "Flash 至少 (KB)",
    "field.ram": "RAM 至少 (KB)",
    "field.pins": "引脚数不超过",
    "field.package": "封装",
    "field.tempMax": "最高工作温度至少 (°C)",
    "field.fdcan": "FDCAN 至少",
    "field.usb": "USB 至少",
    "field.motorTimers": "电机定时器至少",
    "field.hrtim": "HRTIM 至少",
    "field.unknownPolicy": "缺字段策略",
    "opt.unspecified": "不指定",
    "opt.unlimited": "不限制",
    "opt.motor": "电机控制",
    "opt.power": "电源变换",
    "opt.bms": "电池管理",
    "opt.industrial": "工业控制",
    "opt.iot": "物联网",
    "opt.allowRisk": "保留并标出风险",
    "opt.exclude": "库中无证据则排除",
    "ph.frequency": "例如 170",
    "ph.flash": "例如 512",
    "ph.pins": "例如 64",
    "ph.temp": "例如 125",
    "ph.min1": "例如 1",
    "inspect.label": "STM32 订货号",
    "inspect.placeholder": "输入 STM32 开头的系列或订货号",
    "inspect.submit": "查看这颗料",
    "followup.label": "还可以改需求或再问一句",
    "followup.send": "追问",
    "followup.notes": "不承诺价格和交期。硬约束可点上方再改。",
    "followup.placeholder": "例如：再加 USB；相近料从 H5 里找；替换某厂订货号。",
    "followup.placeholderInspect": "例如：推荐 Flash 更大的；查看 STM32G474RET3；替换某厂订货号。",
    "footer.db": "ST MCU Selector · 公开 MCU 数据库短名单",
    "querying": "正在查询公开 MCU 数据库…",
    "processing": "正在处理…",
    "needPrompt": "请先写一句需求、竞品对照或问题。",
    "requestFailed": "请求失败 ({status})",
    "uploadPrompt": "对照上传的规格书",
    "heading.shortlist": "数据库短名单",
    "heading.shortlistCompare": "数据库短名单（含对照）",
    "empty.requirements": "没有满足硬约束的候选。放宽硬约束后再试。",
    "empty.competitor": "数据库没有筛出可对照的 STM32 订货号。",
    "score": "匹配度 {score}",
    "stProduct": "ST 产品页",
    "stCom": "在 st.com 查看",
    "otherPackages": "同系列还有这些封装",
    "rejected": "硬约束剔除 {count} 颗。",
    "notFound": "未找到 {part}。",
    "nearParts": "相近订货号：{list}",
    "compare.freq": "主频 {value} MHz",
    "compare.flash": "Flash {value} KB",
    "compare.ram": "RAM {value} KB",
    "compare.pins": "{value} 引脚",
    "compare.specs": "竞品规格：{bits}。",
    "compare.lead": "对照 {name}。{specs} 下列订货号来自公开 MCU 数据库，不是模型编造。",
    "brief.compare": "竞品对照短名单",
    "brief.analysis": "分析结论",
    "fallback.shortlist": "当前短名单是 {names}。规格见下方卡片。\n\n这是短名单，不是设计签核。封装引脚、外设并发、认证、价格和供货须核对当前 datasheet。",
    "suggest.series": "系列型号",
    "suggest.orderable": "订货号",
    "fact.core": "内核",
    "fact.frequency_mhz": "主频",
    "fact.flash_kb": "Flash",
    "fact.ram_kb": "RAM",
    "fact.package": "封装",
    "fact.package_type": "封装类型",
    "fact.pin_count": "引脚",
    "fact.temperature_min_c": "最低工作温度",
    "fact.temperature_max_c": "最高工作温度",
    "fact.voltage_min_v": "最低电压",
    "fact.voltage_max_v": "最高电压",
    "fact.adc_channels": "ADC 通道",
    "fact.adc_units": "ADC 单元",
    "fact.opamps": "运放",
    "fact.comparators": "比较器",
    "fact.dac_channels": "DAC 通道",
    "fact.can": "CAN",
    "fact.fdcan": "FDCAN",
    "fact.usb": "USB",
    "fact.usb_types": "USB 类型",
    "fact.ethernet": "Ethernet",
    "fact.ethernet_speed_mbps": "Ethernet 速率",
    "fact.motor_timers": "电机定时器",
    "fact.hrtim": "HRTIM",
    "fact.timers": "定时器",
    "fact.timers_16bit": "16 位定时器",
    "fact.timers_32bit": "32 位定时器",
    "fact.timers_8bit": "8 位定时器",
    "fact.fpu": "FPU",
    "fact.firmware_package": "固件包",
    "group.operating": "工作条件",
    "group.comm": "通信接口",
    "group.analog": "模拟与定时",
    "list.security": "安全能力",
    "list.timers": "其他定时功能",
    "inspect.disclaimer": "这是库内身份核对，不是设计签核。封装引脚、外设并发、认证、价格和供货须以 st.com 与最新 datasheet 为准。",
    "status.unknown": "库内状态未标注",
    "status.soon": "即将供货（库内状态，不是可下单承诺）",
    "status.obsolete": "停产（库内状态）",
    "status.nrnd": "不建议用于新设计（库内状态）",
    "status.active": "量产（库内状态）",
    "status.other": "库内状态：{status}",
    "match.positioning": "产品定位：{text}",
    "match.score": "匹配度 {score}。硬约束过筛后，按规格贴合和应用画像扣分。",
    "match.compare": "对照：{row}",
    "match.meet": "满足：{row}",
    "match.penalty": "扣分：{row}",
    "match.risk": "风险：{row}",
    "evidence.compare": "与竞品对照",
    "evidence.match": "匹配度说明",
  },
  en: {
    "tdk.title": "ST MCU Selector | STMicroelectronics",
    "tdk.description": "ST MCU Selector: from must-meet specs, verified competitor parameters, or an STM32 orderable part number, ST’s public MCU database returns up to three candidates. This is a shortlist; check the datasheet before design.",
    "tdk.keywords": "ST MCU Selector, STM32, MCU selection, orderable part number, competitor comparison",
    "db.loading": "Loading device library",
    "db.ready": "Device library ready",
    "db.readyCount": "Device library ready · {count} orderable PNs",
    "db.notReady": "Device library not ready",
    "db.offline": "Cannot reach the selector service",
    "messageBar": "Database matching returns candidates only; at most three orderable part numbers. This is a shortlist, not a design sign-off. Package pins, concurrent peripherals, certification, price, and supply still need the current datasheet.",
    "modes.aria": "Choose a task",
    "lang.aria": "Choose language",
    "tab.recommend.head": "Recommend",
    "tab.recommend.body": "One sentence for a requirement or a competitor part. Returns up to three candidates.",
    "tab.inspect.head": "Look up a part",
    "tab.inspect.body": "See how that STM32 is listed in the library",
    "nl.label": "Describe the need in one sentence",
    "nl.placeholder": "e.g. motor control needs USB; anything close to GD32H779, preferably in H5; replace a competitor PN; look up STM32G474RET3.",
    "nl.notes": "Recommend returns candidates directly. Edit hard constraints on the left. No price or lead-time promise.",
    "nl.notesLlm": "DeepSeek turns this sentence into hard constraints or competitor specs; the database then returns candidates.",
    "nl.notesRules": "Without DeepSeek, keywords are extracted. Recommend still comes from the database.",
    "drop.title": "Optional competitor datasheet PDF or screenshot; you can drop it here.",
    "drop.notes": "Digital file or a clear screenshot, 8 MB max, not stored. If a scan is unreadable, paste key specs into the box.",
    "drop.fileChosen": "File selected",
    "drop.needPdf": "Upload a PDF datasheet or a clear screenshot (PNG / JPG / WebP).",
    "drop.tooLarge": "Keep the file under 8 MB.",
    "drop.ocrImage": "Reading specs from the image…",
    "drop.ocrPdf": "Extracting specs from the datasheet…",
    "submit.recommend": "Recommend",
    "must.summary": "Hard constraints (edit, then Recommend again)",
    "field.application": "Application",
    "field.frequency": "Clock at least (MHz)",
    "field.flash": "Flash at least (KB)",
    "field.ram": "RAM at least (KB)",
    "field.pins": "Pin count at most",
    "field.package": "Package",
    "field.tempMax": "Max operating temperature at least (°C)",
    "field.fdcan": "FDCAN at least",
    "field.usb": "USB at least",
    "field.motorTimers": "Motor timers at least",
    "field.hrtim": "HRTIM at least",
    "field.unknownPolicy": "Missing-field policy",
    "opt.unspecified": "Not specified",
    "opt.unlimited": "No limit",
    "opt.motor": "Motor control",
    "opt.power": "Power conversion",
    "opt.bms": "Battery management",
    "opt.industrial": "Industrial control",
    "opt.iot": "IoT",
    "opt.allowRisk": "Keep and flag risk",
    "opt.exclude": "Exclude if the library has no evidence",
    "ph.frequency": "e.g. 170",
    "ph.flash": "e.g. 512",
    "ph.pins": "e.g. 64",
    "ph.temp": "e.g. 125",
    "ph.min1": "e.g. 1",
    "inspect.label": "STM32 orderable part number",
    "inspect.placeholder": "Type an STM32 series or orderable PN",
    "inspect.submit": "Look up this part",
    "followup.label": "Change the need or ask another question",
    "followup.send": "Follow up",
    "followup.notes": "No price or lead-time promise. Edit hard constraints above if needed.",
    "followup.placeholder": "e.g. add USB; stay in H5 for a close part; replace a competitor PN.",
    "followup.placeholderInspect": "e.g. recommend more Flash; look up STM32G474RET3; replace a competitor PN.",
    "footer.db": "ST MCU Selector · public MCU database shortlist",
    "querying": "Querying the public MCU database…",
    "processing": "Working…",
    "needPrompt": "Write a need, a competitor compare, or a question first.",
    "requestFailed": "Request failed ({status})",
    "uploadPrompt": "Compare the uploaded datasheet",
    "heading.shortlist": "Database shortlist",
    "heading.shortlistCompare": "Database shortlist (with comparison)",
    "empty.requirements": "No candidates meet the hard constraints. Relax them and try again.",
    "empty.competitor": "The database did not return a comparable STM32 orderable PN.",
    "score": "Match {score}",
    "stProduct": "ST product page",
    "stCom": "View on st.com",
    "otherPackages": "Other packages in this series",
    "rejected": "Hard constraints removed {count} parts.",
    "notFound": "Did not find {part}.",
    "nearParts": "Nearby orderable PNs: {list}",
    "compare.freq": "Clock {value} MHz",
    "compare.flash": "Flash {value} KB",
    "compare.ram": "RAM {value} KB",
    "compare.pins": "{value} pins",
    "compare.specs": "Competitor specs: {bits}.",
    "compare.lead": "Compared with {name}. {specs} Part numbers below come from the public MCU database, not from the model.",
    "brief.compare": "Competitor-compare shortlist",
    "brief.analysis": "Analysis",
    "fallback.shortlist": "Current shortlist: {names}. Specs are on the cards below.\n\nThis is a shortlist, not a design sign-off. Package pins, concurrent peripherals, certification, price, and supply need the current datasheet.",
    "suggest.series": "Series",
    "suggest.orderable": "Orderable PN",
    "fact.core": "Core",
    "fact.frequency_mhz": "Clock",
    "fact.flash_kb": "Flash",
    "fact.ram_kb": "RAM",
    "fact.package": "Package",
    "fact.package_type": "Package type",
    "fact.pin_count": "Pins",
    "fact.temperature_min_c": "Min operating temperature",
    "fact.temperature_max_c": "Max operating temperature",
    "fact.voltage_min_v": "Min voltage",
    "fact.voltage_max_v": "Max voltage",
    "fact.adc_channels": "ADC channels",
    "fact.adc_units": "ADC units",
    "fact.opamps": "Op-amps",
    "fact.comparators": "Comparators",
    "fact.dac_channels": "DAC channels",
    "fact.can": "CAN",
    "fact.fdcan": "FDCAN",
    "fact.usb": "USB",
    "fact.usb_types": "USB types",
    "fact.ethernet": "Ethernet",
    "fact.ethernet_speed_mbps": "Ethernet speed",
    "fact.motor_timers": "Motor timers",
    "fact.hrtim": "HRTIM",
    "fact.timers": "Timers",
    "fact.timers_16bit": "16-bit timers",
    "fact.timers_32bit": "32-bit timers",
    "fact.timers_8bit": "8-bit timers",
    "fact.fpu": "FPU",
    "fact.firmware_package": "Firmware package",
    "group.operating": "Operating conditions",
    "group.comm": "Communication",
    "group.analog": "Analog and timers",
    "list.security": "Security",
    "list.timers": "Other timer functions",
    "inspect.disclaimer": "This is an in-library identity check, not a design sign-off. Package pins, concurrent peripherals, certification, price, and supply must follow st.com and the latest datasheet.",
    "status.unknown": "Library status not marked",
    "status.soon": "Coming soon (library status, not an orderable promise)",
    "status.obsolete": "Obsolete (library status)",
    "status.nrnd": "Not recommended for new design (library status)",
    "status.active": "Active (library status)",
    "status.other": "Library status: {status}",
    "match.positioning": "Product positioning: {text}",
    "match.score": "Match {score}. After hard-constraint screening, score is reduced for spec fit and application profile.",
    "match.compare": "Compare: {row}",
    "match.meet": "Meets: {row}",
    "match.penalty": "Penalty: {row}",
    "match.risk": "Risk: {row}",
    "evidence.compare": "Versus competitor",
    "evidence.match": "Match notes",
  },
};
