Object.assign(COPY.zh, {
  "gate.title": "MCU Selector",
  "gate.lead": "ST 内部试用。请输入含 @st.com 的邮箱后进入选型页。",
  "gate.placeholder": "name@st.com",
  "gate.submit": "进入",
  "gate.error": "请输入含 @st.com 的邮箱。",
  "gate.hint": "仅用于进入本页，不创建账号。",
  "table.title": "竞品并列表",
  "table.item": "项目",
  "table.competitor": "竞品",
  "table.verdict": "对比",
  "table.missing": "—",
  "table.near": "接近",
  "table.same": "相同",
  "table.compHigher": "差约 {times} 倍（竞品更高）",
  "table.stHigher": "短名单约高 {times} 倍",
  "table.note": "数字来自竞品规格与公开 MCU 数据库。匹配度是筛后接近程度，不是性能对等。禁止把这里的倍数当成 CoreMark。",
  "app.banner": "应用：{app}。工程判断看库内电机定时器、HRTIM、通信和模拟字段，不是 CubeMX 签核。",
  "score.closeness": "匹配度 {score}（系列内接近，不是性能对等）",
});
Object.assign(COPY.en, {
  "gate.title": "MCU Selector",
  "gate.lead": "ST internal trial. Enter an email containing @st.com to open the selector.",
  "gate.placeholder": "name@st.com",
  "gate.submit": "Enter",
  "gate.error": "Use an email that contains @st.com.",
  "gate.hint": "Used only to open this page. No account is created.",
  "table.title": "Side-by-side vs competitor",
  "table.item": "Item",
  "table.competitor": "Competitor",
  "table.verdict": "Contrast",
  "table.missing": "—",
  "table.near": "Close",
  "table.same": "Same",
  "table.compHigher": "About {times}× (competitor higher)",
  "table.stHigher": "Shortlist about {times}× higher",
  "table.note": "Numbers come from competitor specs and the public MCU database. Match score is closeness after the filter, not performance parity. Do not read these ratios as CoreMark.",
  "app.banner": "Application: {app}. Engineering judgment uses library motor timers, HRTIM, comms, and analog fields — not a CubeMX sign-off.",
  "score.closeness": "Match {score} (in-series closeness, not performance parity)",
});
