Object.assign(COPY.zh, {
  "gate.title": "MCU Selector",
  "gate.lead": "ST 内部试用。请输入含 @st.com 的邮箱后进入选型页。",
  "gate.placeholder": "name@st.com",
  "gate.submit": "进入",
  "gate.error": "请输入含 @st.com 的邮箱。",
  "gate.hint": "仅用于进入本页，不创建账号。",
  "table.title": "竞品并列表",
  "table.item": "项目",
  "table.competitor": "竞品",
  "table.verdict": "对比",
  "table.missing": "—",
  "table.near": "接近",
  "table.same": "相同",
  "table.compHigher": "差约 {times} 倍（竞品更高）",
  "table.stHigher": "短名单约高 {times} 倍",
  "table.note": "数字来自竞品规格与公开 MCU 数据库。匹配度是筛后接近程度，不是性能对等。禁止把这里的倍数当成 CoreMark。",
  "app.banner": "应用：{app}。工程判断看库内电机定时器、HRTIM、通信和模拟字段，不是 CubeMX 签核。",
  "score.closeness": "匹配度 {score}（系列内接近，不是性能对等）",
  "inspect.table": "库内规格",
  "inspect.value": "值",
  "inspect.other": "其他库内字段",
  "inspect.orderables": "同系列订货号",
  "inspect.fromOrderable": "系列型号本身往往没有封装级字段。下表规格来自订货号 {part}，须再核对该订货号 datasheet。",
  "field.i2c": "I2C 至少",
  "field.compact": "封装尽量小",
  "ph.i2c": "例如 3",
  "fact.i2c": "I2C",
  "history.summary": "历史记录",
  "history.empty": "还没有历史。推荐之后会记在这台设备上，点一条可改条件再搜。",
  "history.item": "已保存的条件",
  "export.copy": "复制列表",
  "export.csv": "下载 CSV",
  "export.done": "短名单已复制或已开始下载。",
  "export.failed": "导出失败，请再试一次。",
  "export.empty": "当前没有可导出的订货号。",
  "export.part": "订货号",
  "export.score": "匹配度",
  "export.package": "封装",
  "export.pins": "引脚",
  "export.freq": "主频 MHz",
  "export.flash": "Flash KB",
  "export.ram": "RAM KB",
  "export.status": "库内状态",
  "export.constraints": "硬约束",
  "export.url": "ST 产品页",
});
Object.assign(COPY.en, {
  "gate.title": "MCU Selector",
  "gate.lead": "ST internal trial. Enter an email containing @st.com to open the selector.",
  "gate.placeholder": "name@st.com",
  "gate.submit": "Enter",
  "gate.error": "Use an email that contains @st.com.",
  "gate.hint": "Used only to open this page. No account is created.",
  "table.title": "Side-by-side vs competitor",
  "table.item": "Item",
  "table.competitor": "Competitor",
  "table.verdict": "Contrast",
  "table.missing": "—",
  "table.near": "Close",
  "table.same": "Same",
  "table.compHigher": "About {times}× (competitor higher)",
  "table.stHigher": "Shortlist about {times}× higher",
  "table.note": "Numbers come from competitor specs and the public MCU database. Match score is closeness after the filter, not performance parity. Do not read these ratios as CoreMark.",
  "app.banner": "Application: {app}. Engineering judgment uses library motor timers, HRTIM, comms, and analog fields — not a CubeMX sign-off.",
  "score.closeness": "Match {score} (in-series closeness, not performance parity)",
  "inspect.table": "Library specs",
  "inspect.value": "Value",
  "inspect.other": "Other library fields",
  "inspect.orderables": "Orderable part numbers in this type",
  "inspect.fromOrderable": "The series type often has no package-level fields. Specs below come from orderable PN {part}; confirm that datasheet.",
  "field.i2c": "I2C at least",
  "field.compact": "Prefer a smaller package",
  "ph.i2c": "e.g. 3",
  "fact.i2c": "I2C",
  "history.summary": "History",
  "history.empty": "No history yet. Recommendations are kept on this device. Open one to edit the constraints and search again.",
  "history.item": "Saved constraints",
  "export.copy": "Copy list",
  "export.csv": "Download CSV",
  "export.done": "Shortlist copied, or the download has started.",
  "export.failed": "Export failed. Try again.",
  "export.empty": "There is no orderable part number to export.",
  "export.part": "Orderable PN",
  "export.score": "Match",
  "export.package": "Package",
  "export.pins": "Pins",
  "export.freq": "Clock MHz",
  "export.flash": "Flash KB",
  "export.ram": "RAM KB",
  "export.status": "Library status",
  "export.constraints": "Hard constraints",
  "export.url": "ST product page",
});
